api_url: https://pdt.hcmus.edu.vn/dstn/DSSVTN
headers:
    User-Agent: Mozilla/5.0 (Windows NT 6.1; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/109.0.0.0 Safari/537.36 Edge/109.0.1518.140
results:
    rows: 10
    page: 1
    sord: desc